package com.alianz.practice.alianz_practice.model;

public class ProductData {

    public static final String[] PRODUCT_NAMES = { "Smartphone", "Laptop", "Smartwatch", "Television", "Camera",
            "Headphones", "T-Shirt",
            "Jeans", "Dress Shirt", "Skirt", "Novel", "Cookbook", "Self-Help Book", "Blender", "Toaster",
            "Microwave", "Vacuum Cleaner", "Treadmill", "Dumbbells", "Yoga Mat", "Shampoo", "Skin Cream",
            "Protein Shake", "Energy Bar", "Coffee", "Wine", "Tea", "Sofa", "Dining Table", "Bed Frame",
            "Bookshelf", "Teddy Bear", "Lego Set", "Puzzle", "Necklace", "Bracelet", "Earrings", "Car",
            "Motorcycle", "Bike", "Pet Food", "Pet Toy", "Pet Bed", "Printer", "Scanner", "Desk Lamp", "Notebook",
            "Pen", "Folder", "DVD", "Blu-Ray", "Vinyl Record", "Digital Download" };

    public static final String[] PRODUCT_DESCRIPTIONS = {
            "A powerful handheld device with advanced features for communication and computing.",
            "A portable computer with a keyboard and screen for personal or professional use.",
            "A wearable device with various functionalities like fitness tracking and notifications.",
            "An electronic device with a screen for viewing broadcast television programs.",
            "A device used to capture photographs and videos.",
            "Audio equipment worn on the head to listen to audio content privately.",
            "A garment with short sleeves and a round neckline, typically made of cotton.",
            "A type of pants made of denim fabric.",
            "A formal shirt worn with a suit jacket or blazer.",
            "A garment worn by women or girls that hangs from the waist and covers part of the legs.",
            "A long written fictional narrative.",
            "A book containing recipes and instructions for cooking.",
            "A book providing advice or guidance on personal development or problem-solving.",
            "An appliance used to mix or purée food ingredients.",
            "An appliance used to brown bread by exposing it to radiant heat.",
            "An appliance used to cook or heat food by dielectric heating.",
            "A device used to suck up dirt and dust from floors and surfaces.",
            "A device used for running or walking in one place.",
            "Weights used for physical exercise.",
            "A piece of equipment used for yoga practice.",
            "A hair care product used for cleaning the scalp and hair.",
            "A cosmetic applied to the skin to improve its appearance.",
            "A dietary supplement used for muscle building or recovery.",
            "A snack bar containing ingredients intended to provide a quick energy boost.",
            "A brewed beverage made from roasted coffee beans.",
            "An alcoholic beverage made from fermented grapes.",
            "A beverage made by steeping dried leaves in hot water.",
            "A long upholstered piece of furniture for seating multiple people.",
            "A piece of furniture with a flat top and one or more legs, used as a surface for eating.",
            "A piece of furniture used for sleeping and relaxation.",
            "A piece of furniture with shelves for storing books.",
            "A stuffed toy bear.",
            "A set of interlocking plastic bricks for building models.",
            "A game or toy designed to test ingenuity or knowledge.",
            "A piece of jewelry worn around the neck.",
            "A piece of jewelry worn around the wrist.",
            "A piece of jewelry worn on the earlobe.",
            "A wheeled motor vehicle used for transportation.",
            "A two-wheeled vehicle used for transportation.",
            "A two-wheeled pedal-driven vehicle.",
            "Food formulated and intended for consumption by pets.",
            "A plaything for a pet animal to chew on or play with.",
            "A piece of furniture designed for a pet to sleep on.",
            "A machine used for printing text or images onto paper.",
            "A device used to capture images or documents and convert them into digital format.",
            "A lamp designed for use on a desk.",
            "A book with blank pages for writing notes.",
            "A tool used for writing or drawing with ink.",
            "A folded cover or holder for loose papers.",
            "A digital optical disc storage format.",
            "A digital optical disc storage format for high-definition video.",
            "A format for storing audio recordings on vinyl discs.",
            "A digital file or software available for download from the internet."
    };

    public static final String[] PRODUCT_TYPES = {"ELECTRONICS",
    "CLOTHING",
    "BOOKS",
    "HOME_APPLIANCES",
    "SPORTS_EQUIPMENT",
    "BEAUTY_PRODUCTS",
    "FOOD_AND_DRINKS",
    "FURNITURE",
    "TOYS",
    "JEWELRY",
    "HEALTH_AND_WELLNESS",
    "AUTOMOTIVE",
    "PET_SUPPLIES",
    "OFFICE_SUPPLIES",
    "MUSIC_AND_MEDIA",
    "ART_AND_CRAFTS",
    "OTHER"
    };
}
